pipeline {
    agent {
        label 'docker'
    }

    stages {
        stage('checkout') {
           steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[ name: '*/ready/**' ]],
                    extensions: [
                        [$class: 'CleanBeforeCheckout'],
                        pretestedIntegration(
                            gitIntegrationStrategy: accumulated(),
                            integrationBranch: 'master',
                            repoName: 'origin'
                        )
                    ],
                    userRemoteConfigs: [[
                        credentialsId: 'praqma-thi',
                        url: 'git@github.com:praqma-thi/graze.git'
                    ]]
                ])
            }
        }

        stage ('build') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage ('installDist') {
            steps {
                sh './gradlew installDist'
            }
        }

        stage('publish') {
           steps {
               pretestedIntegrationPublisher()
            }
        }

        stage ('contest') {
            steps {
                script {
                    // Run the game 100 times and store the results
                    def results = [:]
                    100.times {
                        def winner = sh(script: "build/install/graze/bin/graze jenkins/test-config.json", returnStdout: true)
                        results[winner] = (results[winner] ?: 0) + 1
                        results.each { println "${it.key}: ${it.value}"}
                    }

                    // Format the results to a CSV
                    def resultText = "winner,count\n"
                    results.each { resultText += "${it.key},${it.value}\n" }

                    // Write the formatted text to a file
                    writeFile file: 'jenkins/results.csv', text: resultText
                }

                archiveArtifacts 'jenkins/results.csv'
            }
        }
    }
}
